kind: pipeline
type: docker
name: production
trigger:
  branch:
    - master
  event:
    - push
steps:
  - name: build app
    image: plugins/docker
    settings:
      tags: latest
      registry: docker.dorfjungs.io
      repo: docker.dorfjungs.io/davideperozzi/momentum-js-page
      context: ./
      dockerfile: ./Dockerfile
      force_tag: true
      username: { from_secret: dorfjungs_docker_username }
      password: { from_secret: dorfjungs_docker_password }
  - name: deploy
    image: dorfjungs/drone-docker-stack
    settings:
      name: portfolio
      stack: [ .stack.yml ]
      host: davideperozzi.com
      user: root
      key: { from_secret: davideperozzi_ssh_private_key }
    environment:
      APP_DOMAIN: momentum.davideperozzi.com
      APP_IMAGE: docker.dorfjungs.io/davideperozzi/momentum-js-page
      IMAGE_TAG: latest
