version: '3.7'
services:
  app:
    image: ${APP_IMAGE}:${IMAGE_TAG}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.${APP_NAME}_domain_redirect1.redirectregex.regex=^https?://momentum.davide(-|)perozzi.de/(.*)
        - traefik.http.middlewares.${APP_NAME}_domain_redirect1.redirectregex.replacement=https://${APP_DOMAIN}/$${2}
        - traefik.http.routers.${APP_NAME}.entrypoints=https
        - traefik.http.routers.${APP_NAME}.middlewares=trim_www,${APP_NAME}_domain_redirect1
        - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`, `www.${APP_DOMAIN}`, `momentum.davideperozzi.de`, `momentum.davide-perozzi.de`)
        - traefik.http.routers.${APP_NAME}.service=${APP_NAME}
        - traefik.http.routers.${APP_NAME}.tls.certresolver=default1
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=80
    networks:
      - default
      - traefik-public
networks:
  traefik-public:
    external: true
    name: traefik-public
